### ISSUE TITLE
[Feature] Improve ci trigger and cancel

### ISSUE THREAD

**Issue by JingsongLi** [apache/incubator-paimon#951]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1. Multiple commits of the same PR require cancellation of the previous testings
2. The master merged commits cannot cancel the previous testing

But #883 broke the requirement ②.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liugddx** [comment]
Assign to me, i will fix this error .

**Comment by tisonkun** [comment]
Here is what I use for my projects that _can_ fix the issue:

```yml
# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` event
#   github.event.number: set to the number of the pull request if `pull_request` event
#   github.run_id: otherwise, it's a `push` or `schedule` event, only cancel if we rerun the workflow
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: true
```
